import type { Station, Campaign, RentalSession, User, Reward, DashboardStats, TimelineEvent } from './types';

// Use a fixed reference date to avoid hydration mismatches between server/client
// This represents a "snapshot" of the data at a specific point in time
const REFERENCE_DATE = new Date('2024-01-27T14:00:00.000Z');

// Helper to create dates relative to the fixed reference
const hoursAgo = (hours: number) => new Date(REFERENCE_DATE.getTime() - hours * 60 * 60 * 1000);
const daysAgo = (days: number) => new Date(REFERENCE_DATE.getTime() - days * 24 * 60 * 60 * 1000);
const daysFromNow = (days: number) => new Date(REFERENCE_DATE.getTime() + days * 24 * 60 * 60 * 1000);

export const mockStations: Station[] = [
  {
    id: 'STN-A12',
    name: 'Main Stage Hub',
    location: 'Festival Grounds - North Entrance',
    status: 'online',
    totalSlots: 12,
    availableSlots: 8,
    batteryLevel: 92,
    lastPing: hoursAgo(0.1),
    campaignId: 'CMP-001',
  },
  {
    id: 'STN-B07',
    name: 'Food Court Station',
    location: 'Festival Grounds - Central',
    status: 'online',
    totalSlots: 8,
    availableSlots: 3,
    batteryLevel: 78,
    lastPing: hoursAgo(0.2),
    campaignId: 'CMP-001',
  },
  {
    id: 'STN-C03',
    name: 'VIP Lounge',
    location: 'VIP Area - East Wing',
    status: 'online',
    totalSlots: 6,
    availableSlots: 6,
    batteryLevel: 100,
    lastPing: hoursAgo(0.05),
    campaignId: 'CMP-001',
  },
  {
    id: 'STN-D15',
    name: 'Park City Main Hub',
    location: 'Downtown - Main Street',
    status: 'low-battery',
    totalSlots: 10,
    availableSlots: 2,
    batteryLevel: 15,
    lastPing: hoursAgo(0.5),
    campaignId: 'CMP-001',
  },
  {
    id: 'STN-E09',
    name: 'Cinema Lobby',
    location: 'Egyptian Theatre',
    status: 'maintenance',
    totalSlots: 8,
    availableSlots: 0,
    batteryLevel: 45,
    lastPing: hoursAgo(2),
    campaignId: 'CMP-001',
  },
  {
    id: 'STN-F22',
    name: 'Shuttle Stop',
    location: 'Transit Center',
    status: 'offline',
    totalSlots: 6,
    availableSlots: 0,
    batteryLevel: 0,
    lastPing: hoursAgo(24),
    campaignId: 'CMP-001',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'CMP-001',
    name: 'Sundance Merch Reward',
    eventName: 'Sundance Festival 2024',
    startDate: daysAgo(3),
    endDate: daysFromNow(4),
    hourlyRate: 2.00,
    dailyCap: 10.00,
    depositAmount: 25.00,
    rewardThresholdMinutes: 60,
    rewardType: 'voucher',
    rewardValue: 10.00,
    rewardDescription: '€10 voucher for Sundance official merchandise',
    isActive: true,
    totalSessions: 1847,
    totalRewardsIssued: 892,
  },
  {
    id: 'CMP-002',
    name: 'Early Bird Special',
    eventName: 'Sundance Festival 2024',
    startDate: daysAgo(10),
    endDate: daysAgo(4),
    hourlyRate: 1.50,
    dailyCap: 8.00,
    depositAmount: 20.00,
    rewardThresholdMinutes: 45,
    rewardType: 'discount',
    rewardValue: 15,
    rewardDescription: '15% off any food vendor',
    isActive: false,
    totalSessions: 634,
    totalRewardsIssued: 421,
  },
];

export const mockSessions: RentalSession[] = [
  {
    id: 'SES-882194',
    sessionCode: 'VR-882194B',
    stationId: 'STN-A12',
    stationName: 'Main Stage Hub',
    slotNumber: 4,
    userId: 'USR-001',
    userEmail: 'sarah.chen@email.com',
    userName: 'Sarah Chen',
    status: 'active',
    startTime: hoursAgo(0.5),
    depositAmount: 25.00,
    amountCharged: 0,
    amountRefunded: 0,
    paymentMethod: 'Apple Pay',
    paymentStatus: 'authorized',
    rewardStatus: 'pending',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
  },
  {
    id: 'SES-882193',
    sessionCode: 'VR-882193A',
    stationId: 'STN-D15',
    stationName: 'Park City Main Hub',
    slotNumber: 7,
    userId: 'USR-002',
    userEmail: 'marcus.j@gmail.com',
    userName: 'Marcus Johnson',
    status: 'completed',
    startTime: hoursAgo(2),
    endTime: hoursAgo(0.8),
    durationMinutes: 72,
    depositAmount: 25.00,
    amountCharged: 4.00,
    amountRefunded: 25.00,
    paymentMethod: 'Apple Pay',
    paymentStatus: 'refunded',
    rewardStatus: 'issued',
    rewardCode: 'SUNDANCE-POWERDON-2024',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
  },
  {
    id: 'SES-882192',
    sessionCode: 'VR-882192C',
    stationId: 'STN-B07',
    stationName: 'Food Court Station',
    slotNumber: 2,
    userId: 'USR-003',
    userEmail: 'emily.r@outlook.com',
    userName: 'Emily Roberts',
    status: 'active',
    startTime: hoursAgo(1.2),
    depositAmount: 25.00,
    amountCharged: 0,
    amountRefunded: 0,
    paymentMethod: 'Google Pay',
    paymentStatus: 'authorized',
    rewardStatus: 'qualified',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
  },
  {
    id: 'SES-882191',
    sessionCode: 'VR-882191D',
    stationId: 'STN-A12',
    stationName: 'Main Stage Hub',
    slotNumber: 9,
    userId: 'USR-004',
    userEmail: 'david.kim@yahoo.com',
    userName: 'David Kim',
    status: 'completed',
    startTime: hoursAgo(4),
    endTime: hoursAgo(3.5),
    durationMinutes: 30,
    depositAmount: 25.00,
    amountCharged: 2.00,
    amountRefunded: 25.00,
    paymentMethod: 'Credit Card',
    paymentStatus: 'refunded',
    rewardStatus: 'pending',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
  },
  {
    id: 'SES-882190',
    sessionCode: 'VR-882190E',
    stationId: 'STN-C03',
    stationName: 'VIP Lounge',
    slotNumber: 1,
    userId: 'USR-005',
    userEmail: 'lisa.wang@company.com',
    userName: 'Lisa Wang',
    status: 'expired',
    startTime: hoursAgo(26),
    endTime: hoursAgo(2),
    durationMinutes: 1440,
    depositAmount: 25.00,
    amountCharged: 10.00,
    amountRefunded: 0,
    paymentMethod: 'Credit Card',
    paymentStatus: 'captured',
    rewardStatus: 'expired',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
  },
  {
    id: 'SES-882189',
    sessionCode: 'VR-882189F',
    stationId: 'STN-B07',
    stationName: 'Food Court Station',
    slotNumber: 5,
    userId: 'USR-006',
    userEmail: 'alex.m@email.com',
    userName: 'Alex Martinez',
    status: 'completed',
    startTime: hoursAgo(5),
    endTime: hoursAgo(3.5),
    durationMinutes: 90,
    depositAmount: 25.00,
    amountCharged: 4.00,
    amountRefunded: 25.00,
    paymentMethod: 'Apple Pay',
    paymentStatus: 'refunded',
    rewardStatus: 'redeemed',
    rewardCode: 'SUNDANCE-MERCH-8921',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
  },
];

export const mockUsers: User[] = [
  {
    id: 'USR-001',
    email: 'sarah.chen@email.com',
    name: 'Sarah Chen',
    createdAt: daysAgo(2),
    totalRentals: 1,
    totalSpent: 0,
    marketingConsent: true,
    lastRentalDate: hoursAgo(0.5),
  },
  {
    id: 'USR-002',
    email: 'marcus.j@gmail.com',
    name: 'Marcus Johnson',
    createdAt: daysAgo(3),
    totalRentals: 3,
    totalSpent: 12.00,
    marketingConsent: true,
    lastRentalDate: hoursAgo(0.8),
  },
  {
    id: 'USR-003',
    email: 'emily.r@outlook.com',
    name: 'Emily Roberts',
    createdAt: daysAgo(1),
    totalRentals: 1,
    totalSpent: 0,
    marketingConsent: false,
    lastRentalDate: hoursAgo(1.2),
  },
  {
    id: 'USR-004',
    email: 'david.kim@yahoo.com',
    name: 'David Kim',
    createdAt: daysAgo(4),
    totalRentals: 2,
    totalSpent: 6.00,
    marketingConsent: true,
    lastRentalDate: hoursAgo(3.5),
  },
  {
    id: 'USR-005',
    email: 'lisa.wang@company.com',
    name: 'Lisa Wang',
    createdAt: daysAgo(5),
    totalRentals: 1,
    totalSpent: 10.00,
    marketingConsent: false,
    lastRentalDate: hoursAgo(2),
  },
  {
    id: 'USR-006',
    email: 'alex.m@email.com',
    name: 'Alex Martinez',
    createdAt: daysAgo(3),
    totalRentals: 4,
    totalSpent: 18.00,
    marketingConsent: true,
    lastRentalDate: hoursAgo(3.5),
  },
];

export const mockRewards: Reward[] = [
  {
    id: 'RWD-001',
    code: 'SUNDANCE-POWERDON-2024',
    sessionId: 'SES-882193',
    userId: 'USR-002',
    userEmail: 'marcus.j@gmail.com',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
    type: 'voucher',
    value: 10.00,
    description: '€10 voucher for Sundance official merchandise',
    status: 'issued',
    issuedAt: hoursAgo(0.8),
    expiresAt: daysFromNow(1),
  },
  {
    id: 'RWD-002',
    code: 'SUNDANCE-MERCH-8921',
    sessionId: 'SES-882189',
    userId: 'USR-006',
    userEmail: 'alex.m@email.com',
    campaignId: 'CMP-001',
    campaignName: 'Sundance Merch Reward',
    type: 'voucher',
    value: 10.00,
    description: '€10 voucher for Sundance official merchandise',
    status: 'redeemed',
    issuedAt: hoursAgo(3.5),
    expiresAt: daysFromNow(0.5),
    redeemedAt: hoursAgo(2),
    redemptionLocation: 'Merch Booth A - Main Stage',
  },
  {
    id: 'RWD-003',
    code: 'SUNDANCE-FOOD-4521',
    sessionId: 'SES-882185',
    userId: 'USR-007',
    userEmail: 'john.d@email.com',
    campaignId: 'CMP-002',
    campaignName: 'Early Bird Special',
    type: 'discount',
    value: 15,
    description: '15% off any food vendor',
    status: 'expired',
    issuedAt: daysAgo(5),
    expiresAt: daysAgo(1),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalSessions: 1847,
  activeSessions: 23,
  totalRevenue: 4892.00,
  totalDepositsHeld: 575.00,
  totalRewardsIssued: 892,
  totalRewardsRedeemed: 634,
  averageSessionDuration: 68,
  conversionRate: 48.3,
  stationsOnline: 4,
  stationsTotal: 6,
};

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'EVT-001',
    timestamp: hoursAgo(2),
    type: 'scan',
    description: 'QR code scanned at Main Stage Hub',
    metadata: { stationId: 'STN-A12', slotId: '04' },
  },
  {
    id: 'EVT-002',
    timestamp: hoursAgo(1.98),
    type: 'auth',
    description: 'User authenticated via email',
    metadata: { email: 'marcus.j@gmail.com' },
  },
  {
    id: 'EVT-003',
    timestamp: hoursAgo(1.95),
    type: 'payment',
    description: 'Deposit authorized via Apple Pay',
    metadata: { amount: '€25.00', method: 'Apple Pay' },
  },
  {
    id: 'EVT-004',
    timestamp: hoursAgo(1.93),
    type: 'unlock',
    description: 'Power bank unlocked from Slot 04',
    metadata: { slotId: '04', batteryLevel: '94%' },
  },
  {
    id: 'EVT-005',
    timestamp: hoursAgo(0.8),
    type: 'return',
    description: 'Power bank returned to Park City Main Hub',
    metadata: { stationId: 'STN-D15', slotId: '07' },
  },
  {
    id: 'EVT-006',
    timestamp: hoursAgo(0.79),
    type: 'reward',
    description: 'Reward qualified - 72 min session (threshold: 60 min)',
    metadata: { duration: '72 min', threshold: '60 min' },
  },
  {
    id: 'EVT-007',
    timestamp: hoursAgo(0.78),
    type: 'refund',
    description: 'Deposit refunded to Apple Pay',
    metadata: { amount: '€25.00', charged: '€4.00' },
  },
];

// Funnel data for analytics
export const mockFunnelData = [
  { stage: 'QR Scans', count: 3420, percentage: 100 },
  { stage: 'Info Submitted', count: 2890, percentage: 84.5 },
  { stage: 'Payment Authorized', count: 2156, percentage: 63.0 },
  { stage: 'Rental Started', count: 1847, percentage: 54.0 },
  { stage: 'Rental Completed', count: 1724, percentage: 50.4 },
  { stage: 'Reward Qualified', count: 892, percentage: 26.1 },
  { stage: 'Reward Redeemed', count: 634, percentage: 18.5 },
];

// Chart data
export const mockRevenueByDay = [
  { date: 'Mon', revenue: 580, sessions: 198 },
  { date: 'Tue', revenue: 720, sessions: 245 },
  { date: 'Wed', revenue: 890, sessions: 312 },
  { date: 'Thu', revenue: 1050, sessions: 389 },
  { date: 'Fri', revenue: 980, sessions: 356 },
  { date: 'Sat', revenue: 420, sessions: 189 },
  { date: 'Sun', revenue: 252, sessions: 158 },
];

export const mockSessionsByHour = [
  { hour: '00', sessions: 12 },
  { hour: '02', sessions: 8 },
  { hour: '04', sessions: 5 },
  { hour: '06', sessions: 15 },
  { hour: '08', sessions: 45 },
  { hour: '10', sessions: 89 },
  { hour: '12', sessions: 156 },
  { hour: '14', sessions: 198 },
  { hour: '16', sessions: 234 },
  { hour: '18', sessions: 267 },
  { hour: '20', sessions: 189 },
  { hour: '22', sessions: 78 },
];
